name: Build and Release Native Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            target: linuxX64
          - os: windows-latest
            target: mingwX64
          - os: macos-latest
            target: macosX64
          - os: macos-latest
            target: macosArm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '19'

      - name: Set execute permission on gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build for ${{ matrix.target }}
        run: ./gradlew linkReleaseExecutable

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-binary
          path: build/bin/native/releaseExecutable/


  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R ./artifacts


      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./artifacts/**
            ./artifacts/**/*
            ./artifacts/linuxX64-binary/JsonSmith.kexe
            ./artifacts/macosArm64-binary/JsonSmith.kexe
            ./artifacts/mingwX64-binary/JsonSmith.exe

